@startuml
salt
{
    <b>Нахождение минимума
    ..
    Дан массив целых чисел.
    Вернуть позицию наименьшего
    ..
    {/ <u> Решение | <b> Тесты }
    {#
        <b> Ввод     |<b>  Ожидание|<b> Вывод
        (1,2,3,4)    |. 0          |. 0
        (4,3,2,1)    |. 3          |. 3
        <b> (1,-1,0) |. <b>2       |. <b>1
    }
    Выполнено: 67%
    ..
    {[Протестировать]|[Сохранить]}
}
@enduml