@startuml
salt
{
    <b>Нахождение минимума
    ..
    Дан массив целых чисел.
    Вернуть позицию наименьшего
    ..
    Ваши решения
    {#
        .      #|.    <&pie-chart>
        []1     |.  8/15
        []2     |.  9/15
        [X]3    |. 15/15

    }
    ..
    {[<&play-circle> Решить]}
}
@enduml