@startuml
salt
{
    <b>Нахождение минимума
    ..
    Дан массив целых чисел.
    Вернуть позицию наименьшего
    ..
    Ваши решения
    {#
        .      #|Выполнено
        []1     |.         20%
        []2     |.         35%
        [X]3    |.        100%

    }
    ..
    {[<&play-circle> Решить]}
}
@enduml