@startuml
salt
{
    Задачи
    ..
    {#
        <b>  Название           |.|<b>  Автор |.<&calendar>
        [ ]Возведение в степень |.<&play-circle>.|<&person> Сергей   | 14 марта 2017
        [X]Факториал            |.<&play-circle>.|<&person> Алексей  | 2 марта 2017
        [ ]Палиндромы           |.<&play-circle>.|<&person> Михаил   | 7 февраля 2017
        [ ]Выход из лабиринта   |.<&play-circle>.|<&person> Светлана | 15 декабря 2016
        [X]Возведение в степень |.<&play-circle>.|<&person> Сергей   | 29 ноября 2016
    }
    {1|2|3|...|<b>8|...|17}
    ..
    [Предложить свою задачу]
}
@enduml