@startuml
salt
{
    Новая задача
    ..
    {
        <b>Название:|"Нахождение минимума"
        <b>Описание:|*
        "Дан массив целых чисел.    "|*
        "Вернуть позицию наименьшего"|*
    }
    ..
    {/ <b> Шаблон решения | <u>Пример Решения | <u>Тест }
    <b>  public class</b> Foo <b><
    <b>      int</b> minIndex(<b>int</b>[] array) <b><
    <i>          //Пиши код здесь
    <b>          return 0;
    <b>      >
    <b>  >
    --
    {[Протестировать]|[Создать]}
}
@enduml